version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin2
      - DJANGO_SUPERUSER_EMAIL=admin2@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=1234
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py createsuperuser --noinput --username $$DJANGO_SUPERUSER_USERNAME --email $$DJANGO_SUPERUSER_EMAIL 2>/dev/null || true &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume: