# Generated by Django 5.1.4 on 2025-12-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockjournalitem',
            name='movement_type',
            field=models.CharField(choices=[('missing', 'Missing'), ('damaged', 'Damaged'), ('broken', 'Broken'), ('expired', 'Expired')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
