# Generated by Django 5.1.4 on 2025-12-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_stockjournalitem_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
