# Generated by Django 5.1.4 on 2025-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockjournal',
            name='movement_type',
        ),
        migrations.AlterField(
            model_name='stockjournalitem',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('missing', 'Missing'), ('damaged', 'Damaged'), ('broken', 'Broken'), ('expired', 'Expired'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
