# Generated by Django 5.2.4 on 2026-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_batch_purchase_price_alter_batch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_min_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=50),
        ),
    ]
