# Generated by Django 5.2.4 on 2026-01-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_product_quantity_alter_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
