# Generated by Django 5.2.4 on 2025-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_batch_quantity_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingpurchase',
            old_name='data',
            new_name='items_data',
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
