# Generated by Django 5.1.4 on 2026-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0009_alter_saleitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="quantity",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
        ),
    ]
