# Generated by Django 5.2.4 on 2025-08-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_rename_data_pendingpurchase_items_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpurchase',
            name='items_data',
        ),
        migrations.AddField(
            model_name='pendingpurchase',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
