# Generated by Django 5.1.4 on 2026-02-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0010_alter_batch_quantity_alter_purchaseitem_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierpayment",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="is_partial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="remaining_balance",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="pos.purchase",
            ),
        ),
    ]
