# Generated by Django 5.1.4 on 2026-02-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0011_alter_supplierpayment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("cashier", "Cashier"),
                            ("inventory", "Inventory Manager"),
                            ("accountant", "Accountant"),
                            ("sales", "Sales Staff"),
                            ("custom", "Custom Role"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_access_dashboard", models.BooleanField(default=False)),
                ("can_access_pos", models.BooleanField(default=False)),
                ("can_process_sales", models.BooleanField(default=False)),
                ("can_edit_sales", models.BooleanField(default=False)),
                ("can_delete_sales", models.BooleanField(default=False)),
                ("can_view_all_sales", models.BooleanField(default=False)),
                ("can_view_own_sales", models.BooleanField(default=False)),
                ("can_view_products", models.BooleanField(default=False)),
                ("can_add_products", models.BooleanField(default=False)),
                ("can_edit_products", models.BooleanField(default=False)),
                ("can_delete_products", models.BooleanField(default=False)),
                ("can_import_products", models.BooleanField(default=False)),
                ("can_view_inventory", models.BooleanField(default=False)),
                ("can_manage_stock", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_view_purchases", models.BooleanField(default=False)),
                ("can_add_purchases", models.BooleanField(default=False)),
                ("can_edit_purchases", models.BooleanField(default=False)),
                ("can_delete_purchases", models.BooleanField(default=False)),
                ("can_view_customers", models.BooleanField(default=False)),
                ("can_add_customers", models.BooleanField(default=False)),
                ("can_edit_customers", models.BooleanField(default=False)),
                ("can_delete_customers", models.BooleanField(default=False)),
                ("can_view_suppliers", models.BooleanField(default=False)),
                ("can_add_suppliers", models.BooleanField(default=False)),
                ("can_edit_suppliers", models.BooleanField(default=False)),
                ("can_delete_suppliers", models.BooleanField(default=False)),
                ("can_view_sales_reports", models.BooleanField(default=False)),
                ("can_view_inventory_reports", models.BooleanField(default=False)),
                ("can_view_profit_reports", models.BooleanField(default=False)),
                ("can_view_customer_reports", models.BooleanField(default=False)),
                ("can_export_reports", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("can_view_financials", models.BooleanField(default=False)),
                ("can_process_refunds", models.BooleanField(default=False)),
                ("can_view_credit_sales", models.BooleanField(default=False)),
                ("can_process_credit_payments", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("print", "Print"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("id_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("can_override_role", models.BooleanField(default=False)),
                ("custom_permissions", models.JSONField(blank=True, default=dict)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
