# Generated by Django 5.1.4 on 2025-12-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_remove_pendingpurchase_items_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='least_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
