# Generated by Django 5.1.4 on 2026-02-03 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0012_permissiongroup_role_useractivitylog_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("card", "Credit Card"),
                            ("bank", "Bank Transfer"),
                            ("credit", "Credit"),
                            ("multiple", "Multiple Methods"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_payments",
                        to="pos.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="CreditSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_credited",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "quantity_paid",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("is_fully_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_payments",
                        to="pos.saleitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_paid",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "credit_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="pos.creditpayment",
                    ),
                ),
                (
                    "credit_sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="pos.creditsaleitem",
                    ),
                ),
            ],
        ),
    ]
