# Generated by Django 5.1.4 on 2025-12-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_product_least_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
