# Generated by Django 5.1.4 on 2026-02-20 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_creditpayment_creditsaleitem_creditpaymentdetail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["expiry_date", "batch_number"]},
        ),
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="purchase_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batch",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
