# Generated by Django 5.1.4 on 2026-02-23 05:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0014_alter_batch_options_batch_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batch",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="pos.purchase",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="purchase_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_ref",
                to="pos.purchaseitem",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="is_fully_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="remaining_quantity",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleitem",
            name="purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="pos.purchaseitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="batch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_item_source",
                to="pos.batch",
            ),
        ),
    ]
