# Generated by Django 5.1.4 on 2026-09-09 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_customer_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('rent', 'RENT'), ('token', 'TOKEN'), ('water', 'WATER'), ('airtime', 'AIRTIME'), ('fixes', 'FIXES'), ('transport', 'TRANSPORT'), ('muhindi_mweusi', 'MUHINDI MWEUSI'), ('transactions', 'TRANSACTIONS'), ('packaging', 'PACKAGING'), ('salary', 'SALARY'), ('vat', 'VAT'), ('discounts', 'DISCOUNTS'), ('remuneration', 'REMUNERATION'), ('tithe', 'TITHE'), ('system', 'SYSTEM'), ('wup', 'WUP'), ('succeed', 'SUCCEED'), ('council', 'COUNCIL'), ('soda_glass', 'SODA GLASS'), ('soda_crate', 'SODA CRATE'), ('token_2', 'TOKEN 2'), ('other', 'OTHER')], max_length=50),
        ),
    ]
